[2021-06-21 19:00:42,304] {scheduler_job.py:182} INFO - Started process (PID=159) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:00:42,305] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:00:42,306] {logging_mixin.py:104} INFO - [2021-06-21 19:00:42,306] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:00:42,311] {logging_mixin.py:104} INFO - [2021-06-21 19:00:42,310] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:00:42,311] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:00:42,327] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.026 seconds
[2021-06-21 19:01:12,494] {scheduler_job.py:182} INFO - Started process (PID=224) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:12,495] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:01:12,496] {logging_mixin.py:104} INFO - [2021-06-21 19:01:12,495] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:12,500] {logging_mixin.py:104} INFO - [2021-06-21 19:01:12,499] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:01:12,500] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:12,525] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.034 seconds
[2021-06-21 19:01:43,641] {scheduler_job.py:182} INFO - Started process (PID=305) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:43,642] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:01:43,642] {logging_mixin.py:104} INFO - [2021-06-21 19:01:43,642] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:43,645] {logging_mixin.py:104} INFO - [2021-06-21 19:01:43,645] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:01:43,646] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:01:43,658] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.019 seconds
[2021-06-21 19:02:13,903] {scheduler_job.py:182} INFO - Started process (PID=369) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:13,904] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:02:13,905] {logging_mixin.py:104} INFO - [2021-06-21 19:02:13,904] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:13,908] {logging_mixin.py:104} INFO - [2021-06-21 19:02:13,908] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:02:13,909] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:13,939] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.038 seconds
[2021-06-21 19:02:44,222] {scheduler_job.py:182} INFO - Started process (PID=450) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:44,224] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:02:44,225] {logging_mixin.py:104} INFO - [2021-06-21 19:02:44,225] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:44,232] {logging_mixin.py:104} INFO - [2021-06-21 19:02:44,231] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:02:44,233] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:02:44,273] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.057 seconds
[2021-06-21 19:03:14,447] {scheduler_job.py:182} INFO - Started process (PID=516) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:14,448] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:03:14,449] {logging_mixin.py:104} INFO - [2021-06-21 19:03:14,449] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:14,451] {logging_mixin.py:104} INFO - [2021-06-21 19:03:14,451] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:03:14,452] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:14,490] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.045 seconds
[2021-06-21 19:03:44,607] {scheduler_job.py:182} INFO - Started process (PID=596) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:44,607] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:03:44,608] {logging_mixin.py:104} INFO - [2021-06-21 19:03:44,608] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:44,611] {logging_mixin.py:104} INFO - [2021-06-21 19:03:44,610] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:03:44,611] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:03:44,646] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.042 seconds
[2021-06-21 19:04:14,663] {scheduler_job.py:182} INFO - Started process (PID=659) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:14,664] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:04:14,664] {logging_mixin.py:104} INFO - [2021-06-21 19:04:14,664] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:14,667] {logging_mixin.py:104} INFO - [2021-06-21 19:04:14,666] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:04:14,668] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:14,680] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:04:44,874] {scheduler_job.py:182} INFO - Started process (PID=739) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:44,875] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:04:44,875] {logging_mixin.py:104} INFO - [2021-06-21 19:04:44,875] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:44,879] {logging_mixin.py:104} INFO - [2021-06-21 19:04:44,879] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:04:44,879] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:04:44,892] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.021 seconds
[2021-06-21 19:05:15,794] {scheduler_job.py:182} INFO - Started process (PID=812) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:15,795] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:05:15,796] {logging_mixin.py:104} INFO - [2021-06-21 19:05:15,796] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:15,798] {logging_mixin.py:104} INFO - [2021-06-21 19:05:15,798] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:05:15,799] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:15,811] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.019 seconds
[2021-06-21 19:05:46,400] {scheduler_job.py:182} INFO - Started process (PID=884) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:46,401] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:05:46,401] {logging_mixin.py:104} INFO - [2021-06-21 19:05:46,401] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:46,405] {logging_mixin.py:104} INFO - [2021-06-21 19:05:46,404] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:05:46,405] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:05:46,418] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:06:16,691] {scheduler_job.py:182} INFO - Started process (PID=965) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:16,692] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:06:16,692] {logging_mixin.py:104} INFO - [2021-06-21 19:06:16,692] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:16,696] {logging_mixin.py:104} INFO - [2021-06-21 19:06:16,695] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:06:16,696] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:16,709] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:06:47,044] {scheduler_job.py:182} INFO - Started process (PID=1029) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:47,045] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:06:47,045] {logging_mixin.py:104} INFO - [2021-06-21 19:06:47,045] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:47,048] {logging_mixin.py:104} INFO - [2021-06-21 19:06:47,048] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:06:47,048] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:06:47,061] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:07:17,277] {scheduler_job.py:182} INFO - Started process (PID=1109) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:17,278] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:07:17,278] {logging_mixin.py:104} INFO - [2021-06-21 19:07:17,278] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:17,281] {logging_mixin.py:104} INFO - [2021-06-21 19:07:17,281] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:07:17,282] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:17,295] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:07:47,600] {scheduler_job.py:182} INFO - Started process (PID=1173) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:47,601] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:07:47,602] {logging_mixin.py:104} INFO - [2021-06-21 19:07:47,602] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:47,605] {logging_mixin.py:104} INFO - [2021-06-21 19:07:47,604] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:07:47,605] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:07:47,618] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:08:18,031] {scheduler_job.py:182} INFO - Started process (PID=1254) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:18,031] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:08:18,032] {logging_mixin.py:104} INFO - [2021-06-21 19:08:18,032] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:18,035] {logging_mixin.py:104} INFO - [2021-06-21 19:08:18,034] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:08:18,035] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:18,048] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:08:48,633] {scheduler_job.py:182} INFO - Started process (PID=1319) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:48,635] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:08:48,635] {logging_mixin.py:104} INFO - [2021-06-21 19:08:48,635] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:48,641] {logging_mixin.py:104} INFO - [2021-06-21 19:08:48,640] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:08:48,642] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:08:48,672] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.042 seconds
[2021-06-21 19:09:18,968] {scheduler_job.py:182} INFO - Started process (PID=1403) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:18,969] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:09:18,969] {logging_mixin.py:104} INFO - [2021-06-21 19:09:18,969] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:18,973] {logging_mixin.py:104} INFO - [2021-06-21 19:09:18,972] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:09:18,973] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:18,986] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:09:49,461] {scheduler_job.py:182} INFO - Started process (PID=1468) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:49,462] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:09:49,463] {logging_mixin.py:104} INFO - [2021-06-21 19:09:49,463] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:49,466] {logging_mixin.py:104} INFO - [2021-06-21 19:09:49,465] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:09:49,466] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:09:49,508] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.050 seconds
[2021-06-21 19:10:19,801] {scheduler_job.py:182} INFO - Started process (PID=1548) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:19,802] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:10:19,803] {logging_mixin.py:104} INFO - [2021-06-21 19:10:19,803] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:19,808] {logging_mixin.py:104} INFO - [2021-06-21 19:10:19,807] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:10:19,808] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:19,846] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.048 seconds
[2021-06-21 19:10:50,142] {scheduler_job.py:182} INFO - Started process (PID=1614) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:50,143] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:10:50,144] {logging_mixin.py:104} INFO - [2021-06-21 19:10:50,144] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:50,148] {logging_mixin.py:104} INFO - [2021-06-21 19:10:50,147] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:10:50,148] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:10:50,186] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.046 seconds
[2021-06-21 19:11:20,454] {scheduler_job.py:182} INFO - Started process (PID=1694) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:20,455] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:11:20,456] {logging_mixin.py:104} INFO - [2021-06-21 19:11:20,456] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:20,462] {logging_mixin.py:104} INFO - [2021-06-21 19:11:20,461] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:11:20,462] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:20,517] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.067 seconds
[2021-06-21 19:11:50,577] {scheduler_job.py:182} INFO - Started process (PID=1759) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:50,578] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:11:50,578] {logging_mixin.py:104} INFO - [2021-06-21 19:11:50,578] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:50,582] {logging_mixin.py:104} INFO - [2021-06-21 19:11:50,581] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:11:50,582] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:11:50,597] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.023 seconds
[2021-06-21 19:12:20,914] {scheduler_job.py:182} INFO - Started process (PID=1840) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:20,915] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:12:20,916] {logging_mixin.py:104} INFO - [2021-06-21 19:12:20,916] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:20,920] {logging_mixin.py:104} INFO - [2021-06-21 19:12:20,920] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:12:20,921] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:20,941] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.038 seconds
[2021-06-21 19:12:51,064] {scheduler_job.py:182} INFO - Started process (PID=1905) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:51,065] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:12:51,066] {logging_mixin.py:104} INFO - [2021-06-21 19:12:51,066] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:51,069] {logging_mixin.py:104} INFO - [2021-06-21 19:12:51,069] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:12:51,070] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:12:51,083] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.021 seconds
[2021-06-21 19:13:21,186] {scheduler_job.py:182} INFO - Started process (PID=1979) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:21,187] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:13:21,188] {logging_mixin.py:104} INFO - [2021-06-21 19:13:21,187] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:21,191] {logging_mixin.py:104} INFO - [2021-06-21 19:13:21,190] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:13:21,192] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:21,206] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.022 seconds
[2021-06-21 19:13:51,740] {scheduler_job.py:182} INFO - Started process (PID=2054) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:51,741] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:13:51,742] {logging_mixin.py:104} INFO - [2021-06-21 19:13:51,742] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:51,745] {logging_mixin.py:104} INFO - [2021-06-21 19:13:51,744] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:13:51,745] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:13:51,758] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:14:21,927] {scheduler_job.py:182} INFO - Started process (PID=2120) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:21,928] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:14:21,928] {logging_mixin.py:104} INFO - [2021-06-21 19:14:21,928] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:21,931] {logging_mixin.py:104} INFO - [2021-06-21 19:14:21,930] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:14:21,932] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:21,944] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:14:52,475] {scheduler_job.py:182} INFO - Started process (PID=2200) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:52,476] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:14:52,477] {logging_mixin.py:104} INFO - [2021-06-21 19:14:52,477] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:52,480] {logging_mixin.py:104} INFO - [2021-06-21 19:14:52,479] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:14:52,480] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:14:52,493] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.020 seconds
[2021-06-21 19:15:23,334] {scheduler_job.py:182} INFO - Started process (PID=2279) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:23,335] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:15:23,336] {logging_mixin.py:104} INFO - [2021-06-21 19:15:23,336] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:23,340] {logging_mixin.py:104} INFO - [2021-06-21 19:15:23,339] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:15:23,340] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:23,355] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.024 seconds
[2021-06-21 19:15:54,212] {scheduler_job.py:182} INFO - Started process (PID=2355) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:54,213] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:15:54,214] {logging_mixin.py:104} INFO - [2021-06-21 19:15:54,214] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:54,218] {logging_mixin.py:104} INFO - [2021-06-21 19:15:54,217] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:15:54,219] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:15:54,240] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.032 seconds
[2021-06-21 19:16:25,016] {scheduler_job.py:182} INFO - Started process (PID=2436) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:25,017] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:16:25,018] {logging_mixin.py:104} INFO - [2021-06-21 19:16:25,018] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:25,022] {logging_mixin.py:104} INFO - [2021-06-21 19:16:25,021] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:16:25,022] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:25,055] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.041 seconds
[2021-06-21 19:16:55,199] {scheduler_job.py:182} INFO - Started process (PID=2501) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:55,200] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:16:55,201] {logging_mixin.py:104} INFO - [2021-06-21 19:16:55,201] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:55,204] {logging_mixin.py:104} INFO - [2021-06-21 19:16:55,203] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:16:55,204] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:16:55,241] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.045 seconds
[2021-06-21 19:17:25,419] {scheduler_job.py:182} INFO - Started process (PID=2580) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:25,420] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:17:25,421] {logging_mixin.py:104} INFO - [2021-06-21 19:17:25,420] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:25,423] {logging_mixin.py:104} INFO - [2021-06-21 19:17:25,423] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:17:25,424] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:25,458] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.041 seconds
[2021-06-21 19:17:55,782] {scheduler_job.py:182} INFO - Started process (PID=2645) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:55,786] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:17:55,788] {logging_mixin.py:104} INFO - [2021-06-21 19:17:55,788] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:55,800] {logging_mixin.py:104} INFO - [2021-06-21 19:17:55,798] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:17:55,801] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:17:55,866] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.092 seconds
[2021-06-21 19:18:26,621] {scheduler_job.py:182} INFO - Started process (PID=2730) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:26,623] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:18:26,623] {logging_mixin.py:104} INFO - [2021-06-21 19:18:26,623] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:26,636] {logging_mixin.py:104} INFO - [2021-06-21 19:18:26,632] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:18:26,637] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:26,665] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.057 seconds
[2021-06-21 19:18:57,396] {scheduler_job.py:182} INFO - Started process (PID=2794) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:57,397] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:18:57,398] {logging_mixin.py:104} INFO - [2021-06-21 19:18:57,398] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:57,402] {logging_mixin.py:104} INFO - [2021-06-21 19:18:57,401] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:18:57,402] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:18:57,418] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.025 seconds
[2021-06-21 19:19:28,161] {scheduler_job.py:182} INFO - Started process (PID=2878) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:28,162] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:19:28,162] {logging_mixin.py:104} INFO - [2021-06-21 19:19:28,162] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:28,167] {logging_mixin.py:104} INFO - [2021-06-21 19:19:28,166] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:19:28,167] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:28,183] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.025 seconds
[2021-06-21 19:19:58,874] {scheduler_job.py:182} INFO - Started process (PID=2942) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:58,876] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:19:58,877] {logging_mixin.py:104} INFO - [2021-06-21 19:19:58,877] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:58,884] {logging_mixin.py:104} INFO - [2021-06-21 19:19:58,883] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:19:58,885] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:19:58,903] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.035 seconds
[2021-06-21 19:20:29,516] {scheduler_job.py:182} INFO - Started process (PID=3024) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:20:29,518] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:20:29,519] {logging_mixin.py:104} INFO - [2021-06-21 19:20:29,519] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:20:29,523] {logging_mixin.py:104} INFO - [2021-06-21 19:20:29,522] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:20:29,523] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:20:29,545] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.032 seconds
[2021-06-21 19:21:00,238] {scheduler_job.py:182} INFO - Started process (PID=3088) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:00,239] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:21:00,240] {logging_mixin.py:104} INFO - [2021-06-21 19:21:00,240] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:00,244] {logging_mixin.py:104} INFO - [2021-06-21 19:21:00,243] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:21:00,245] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:00,264] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.028 seconds
[2021-06-21 19:21:30,815] {scheduler_job.py:182} INFO - Started process (PID=3171) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:30,817] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:21:30,819] {logging_mixin.py:104} INFO - [2021-06-21 19:21:30,819] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:30,827] {logging_mixin.py:104} INFO - [2021-06-21 19:21:30,826] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:21:30,828] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:21:30,844] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.038 seconds
[2021-06-21 19:22:01,483] {scheduler_job.py:182} INFO - Started process (PID=3235) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:01,485] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:22:01,486] {logging_mixin.py:104} INFO - [2021-06-21 19:22:01,485] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:01,489] {logging_mixin.py:104} INFO - [2021-06-21 19:22:01,488] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:22:01,489] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:01,503] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.023 seconds
[2021-06-21 19:22:32,055] {scheduler_job.py:182} INFO - Started process (PID=3318) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:32,055] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:22:32,056] {logging_mixin.py:104} INFO - [2021-06-21 19:22:32,056] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:32,059] {logging_mixin.py:104} INFO - [2021-06-21 19:22:32,058] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:22:32,059] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:22:32,091] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.038 seconds
[2021-06-21 19:23:02,248] {scheduler_job.py:182} INFO - Started process (PID=3381) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:02,249] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:23:02,249] {logging_mixin.py:104} INFO - [2021-06-21 19:23:02,249] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:02,254] {logging_mixin.py:104} INFO - [2021-06-21 19:23:02,253] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:23:02,254] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:02,286] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.041 seconds
[2021-06-21 19:23:32,783] {scheduler_job.py:182} INFO - Started process (PID=3462) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:32,784] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:23:32,784] {logging_mixin.py:104} INFO - [2021-06-21 19:23:32,784] {dagbag.py:487} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:32,787] {logging_mixin.py:104} INFO - [2021-06-21 19:23:32,787] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/udac_example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 317, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/udac_example_dag.py", line 5, in <module>
    from airflow.operators import (StageToRedshiftOperator, LoadFactOperator,
ImportError: cannot import name 'StageToRedshiftOperator'
[2021-06-21 19:23:32,788] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:23:32,823] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/udac_example_dag.py took 0.042 seconds
[2021-06-21 19:42:12,215] {scheduler_job.py:155} INFO - Started process (PID=60) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:12,220] {scheduler_job.py:1573} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:42:12,220] {logging_mixin.py:120} INFO - [2021-06-21 19:42:12,220] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:12,230] {scheduler_job.py:1585} INFO - DAG(s) dict_keys(['udac_example_dag']) retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:12,246] {scheduler_job.py:167} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dag.last_scheduler_run does not exist
LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 159, in _run_file_processor
    pickle_dags)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 1593, in process_file
    dag.sync_to_db()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1515, in sync_to_db
    DagModel).filter(DagModel.dag_id == self.dag_id).first()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.last_scheduler_run does not exist
LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_s...
                                                             ^

[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval 
FROM dag 
WHERE dag.dag_id = %(dag_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'dag_id_1': 'udac_example_dag', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-06-21 19:42:24,461] {scheduler_job.py:155} INFO - Started process (PID=100) to work on /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:24,463] {scheduler_job.py:1573} INFO - Processing file /opt/airflow/dags/udac_example_dag.py for tasks to queue
[2021-06-21 19:42:24,464] {logging_mixin.py:120} INFO - [2021-06-21 19:42:24,464] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:24,469] {scheduler_job.py:1585} INFO - DAG(s) dict_keys(['udac_example_dag']) retrieved from /opt/airflow/dags/udac_example_dag.py
[2021-06-21 19:42:24,480] {scheduler_job.py:167} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dag.last_scheduler_run does not exist
LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 159, in _run_file_processor
    pickle_dags)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 1593, in process_file
    dag.sync_to_db()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 1515, in sync_to_db
    DagModel).filter(DagModel.dag_id == self.dag_id).first()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.last_scheduler_run does not exist
LINE 1: ...AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_s...
                                                             ^

[SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval 
FROM dag 
WHERE dag.dag_id = %(dag_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'dag_id_1': 'udac_example_dag', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
